# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs Arduino Compiler
      # see https://github.com/arduino/compile-sketches
      #see https://github.com/arduino-libraries/Arduino_ConnectionHandler/blob/master/.github/workflows/compile-examples.yml      
      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          verbose: true
          platforms: |
            # Install ESP8266 platform via Boards Manager
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
              version: 2.5.0
          fqbn: esp8266:esp8266:huzzah # esp8266:esp8266:nodemcuv2
          # libraries: ${{ env.LIBRARIES }}
          # size-report-sketch: 'ConnectionHandlerDemo'
          # enable-size-deltas-report: 'true'
          # sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
